name: .NET

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
                dotnet-version: 8.0.x

        - name: Build
          run: |
            cd AspNetCore8CI
            dotnet build --no-restore

        - name: Publish
          run: |
            cd AspNetCore8CI
            dotnet publish --no-build --configuration Release -o output

        - name: Publish Artifact
          uses: actions/upload-artifact@v2
          with:
            name: MyArtifact
            path: ./output
